services:
  mysql:
    image: mysql:8
    container_name: ${PROJECT_NAME:-official}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-official}
      TZ: Asia/Shanghai
    ports:
      - "${MYSQL_PORT:-3306}:${MYSQL_PORT:-3306}"
    volumes:
      - /home/boyuan-official/official/volumes/mysql_data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - /home/boyuan-official/official/db:/docker-entrypoint-initdb.d:ro
    restart: always
    networks:
      - official-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME:-official}-redis
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - /home/boyuan-official/official/volumes/redis_data:/data
    restart: always
    networks:
      - official-network

  official:
    image: ${DOCKERHUB_USERNAME:-boyuanclub}/official-core-api:latest  # 使用Docker Hub镜像
    container_name: ${PROJECT_NAME:-official}-app
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - /home/boyuan-official/official/volumes/uploads:/official/uploads
      - /home/boyuan-official/official/logs:/official/logs
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - DB_NAME=${DB_NAME:-official}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - JWT_SECRET=${JWT_SECRET:-30b264511df560046ae9907e50cd6e69a3cb94ce987538fb2c90b98c70ce684a}
      - MAIL_HOST=${MAIL_HOST:-smtp.feishu.cn}
      - MAIL_PORT=${MAIL_PORT:-465}
      - MAIL_USERNAME=${MAIL_USERNAME:-notify@boyuan.club}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-12bGmEWjvyRDjzxE}
      - SERVER_PORT=8080
      # 添加中文环境支持
      - LANG=zh_CN.UTF-8
      - LANGUAGE=zh_CN:zh
      - LC_ALL=zh_CN.UTF-8
      # 添加JVM参数以支持UTF-8编码和字体处理
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Djava.awt.headless=true -Djava.awt.fontconfig=/etc/fonts/fonts.conf -Dsun.java2d.fontpath=/usr/share/fonts
    # 移除了command行，因为已经在Dockerfile中定义了ENTRYPOINT
    depends_on:
      - mysql
      - redis
    networks:
      - official-network

networks:
  official-network:
    driver: bridge