services:
  # MySQL数据库服务
  mysql:
    image: mysql:8
    container_name: official-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-123}
      MYSQL_DATABASE: official
    ports:
      - "3307:3306"
    volumes:
      - "/usr/local/mysql/data:/var/lib/mysql"
      - "/usr/local/mysql/conf:/etc/mysql/conf.d"
      - "/usr/local/mysql/init:/docker-entrypoint-initdb.d"
    restart: always
    networks:
      - official-network

  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: official-redis
    ports:
      - "6379:6379"
    volumes:
      - "/usr/local/redis/data:/data"
    restart: always
    networks:
      - official-network

  # 应用服务
  official:
    build: .
    container_name: official-app
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - JWT_SECRET=${JWT_SECRET:-bbe0ac1a5b8a113b4568d55c76fe887a1cd99b01acfad7957156945688e03e20}
      - MAIL_HOST=${MAIL_HOST:-smtp.feishu.cn}
      - MAIL_PORT=${MAIL_PORT:-465}
      - MAIL_USERNAME=${MAIL_USERNAME:-notify@boyuan.club}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-12bGmEWjvyRDjzxE}
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - official-network

# 网络定义
networks:
  official-network:
    driver: bridge