spring:
  application:
    name: Official
  datasource:
    url: jdbc:mysql://mysql:${MYSQL_PORT}/${DB_NAME}?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms
  servlet:
    multipart:
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: club.boyuan.official.entity
  configuration:
    mapUnderscoreToCamelCase: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

sms:
  access-key: ${SMS_ACCESS_KEY:your-sms-access-key}
  secret-key: ${SMS_SECRET_KEY:your-sms-secret-key}
  template-id:
    verification-code: ${SMS_TEMPLATE_ID_VERIFICATION:your-sms-template-id}
  region-id: ${SMS_REGION_ID:your-sms-region-id}
  verification-code:
    length: 6
    expiration-minutes: 5