name: Push to Docker Hub on main branch merge

# 定义工作流触发条件
on:
  # 当推送到main分支时触发
  push:
    branches:
      - main
  # 允许从Actions页面手动触发
  workflow_dispatch:

# 定义环境变量
env:
  DOCKER_USERNAME: boyuanclub
  IMAGE_NAME: official
  DOCKERHUB_EMAIL: notify@boyuan.club

# 定义工作流任务
jobs:
  # 构建和推送任务
  build-and_push:
    # 运行环境为Ubuntu最新版
    runs-on: ubuntu-latest
    
    # 定义任务步骤
    steps:
      # 步骤1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        
      # 步骤2: 设置Java环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      # 步骤3: 构建项目
      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests
          
      # 步骤4: 设置Docker Buildx（用于构建Docker镜像）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # 步骤5: 登录到Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # 步骤6: 提取项目版本号
      - name: Extract Maven project version
        run: echo "VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          
      # 步骤7: 构建并推送Docker镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}